### ISSUE TITLE
Provide a git branch for Debian jessie/sid

### ISSUE THREAD

**Issue by ghost** [zfsonlinux/pkg-zfs#112]
The trusty branch ~~seems to work~~ crashes and burns, wouldn't it be better to have a newer Debian branch?

**Comment by FransUrbo** [comment]
> The trusty branch seems to work, but wouldn't it be better to have a newer Debian branch?
> 
> Yes it would. But unfortunately I don't have the resources at the moment to do this. Also, it was supposed to be done by Debian GNU/Linux, but they've stalled (the ZoL packages is in the incoming queue held hostage there for unknown reasons).

**Comment by toobuntu** [comment]
On Jun 4, 2014, at 8:56 AM, Turbo Fredriksson notifications@github.com wrote:

> > The trusty branch seems to work, but wouldn't it be better to have a newer Debian branch? 
> > 
> > Yes it would. But unfortunately I don't have the resources at the moment to do this. Also, it was supposed to be done by Debian GNU/Linux, but they've stalled (the ZoL packages is in the incoming queue held hostage there for unknown reasons).

Is the staging repo up to date. Can we build our own debs from there or should we use the upstream git repo? I am reluctant to do that because I don't like the idea of building kmod rpms and converting to debs using alien if they can instead be built using the intended Debian build infrastructure. 

As far as the reasons, from what I gather there are two primary ones. First, getting a decision about the licensing in relation to the dfsg--though this might be sorted out now, I'm not entirely sure. Second, eliminating or reducing the delta between kfreebsd and linux zfs packages, and resolving all "conflicts" among them. Doesn't look like anyone's started to tinker with adding zfs support to the debian-installer for linux, either. It's already supported for kfreebsd. Are udebs buildable for the debian installer?

**Comment by FransUrbo** [comment]
> Is the staging repo up to date. Can we build our own debs from there or should we use the upstream git repo?

How do you mean? Which staging repo?

The one in Debian GNU/Linux is _way_ behind pkg-{zfs,spl}, both [ZoL] code vice and debian directory. They haven't done anything since they uploaded the first version to the incoming queue - they're waiting for a ruling.

> I am reluctant to do that because I don't like the idea of building kmod rpms and converting to debs using alien

That is what pkg-{zfs,spl} is for. It's intended to be the (native) packaging repository for ZoL. It will build all the packages using debuild, not rpm->deb.

For Jessie/Sid, you _should_ be able to use the latest Wheezy tag without much modification. At least try it, and let me know.

> As far as the reasons, from what I gather there are two primary ones.

You have misunderstood. That is simply conjecture - what other people thing, believe what COULD happen.

We have yet to get an answer from the FTP maintainers.

> Doesn't look like anyone's started to tinker with adding zfs support to the debian-installer for linux,

On the contrary. I started AND finished this over a year ago. It supported zfs on root and everything (including support for the crypto patch, which I use/-d at the time). The patches just haven't been accepted (because there's no point - no ZoL in Debian GNU/Linux yet).

**Comment by ghost** [comment]
@FransUrbo Reading https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686447, it seems like the only issue left is whether the kFreeBSD package will conflict with your packages. It seems like it would be appropriate to test this in Debian experimental, but I'm not sure.

An older version of spl-dkms is available in the archives already: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686453

**Comment by FransUrbo** [comment]
> Reading https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686447, it seems like the only issue left is whether the kFreeBSD package will conflict with your packages.
> 
> As I've said, this is still conjectures. Mainly from the kFreeBSD maintainer which have opinions about the fact that the Linux packages have the same name as the kFreeBSD ones, despite not being built from the same source.

I have maintained that this is not explicitly forbidden, and should therefor be allowed (considering that it shared the same codebase once, still contain _a lot_ of identical code and will be one code once again in a hopefully not to distant future).

The _belief_ is that this isn't allowed, but _NONE_ have been able to point any where near a [packaging] guideline point about this. And until this is clearly settled (by the FTP maintainers!), then the ZoL maintainers in Debian GNU/Linux is unwilling to do anything.

> An older version of spl-dkms is available in the archives already

No point in uploading a newer version av spl, since there's no zfs package that require it (which is the only one needing/requiring spl).

**Comment by toobuntu** [comment]
> Doesn't look like anyone's started to tinker with adding zfs support to the debian-installer for linux,
> On the contrary. I started AND finished this over a year ago. It supported zfs on root and everything (including support for the crypto patch, which I use/-d at the time). The patches just haven't been accepted (because there's no point - no ZoL in Debian GNU/Linux yet).

So if I build partman-zfs version 28 (only changes since then are language support anyway, version 29 reverted the linux support), should I be able to anna-install it and have a d-i that will allow me to install to zfs?

**Comment by FransUrbo** [comment]
No, since the patches I wrote haven't been accepted.

**Comment by FransUrbo** [comment]
Closing this. There is tags for both Wheezy and Jessie, Released and Dailies in the pkg-{zfs,spl} repo.
