### ISSUE TITLE
sparse file vdevs on samba cifs mount cause deadlock (non-responsive txg_sync) at shutdown

### ISSUE THREAD

**Issue by krichter722** [zfsonlinux/pkg-zfs#124]
This might be prevented by adding upstart or systemd hooks exporting the pool (and consequently importing it at startup) or some other mechanism of preventing the deadlock.

Using 0.6.3 on Ubuntu 14.10 amd64 with mount.cifs 6.0.

**Comment by dajhorn** [comment]
@krichter722, this is a known deficiency in the Ubuntu init stack that also affects regular filesystems like ext4.  Instead, try exporting the sparse files through something like iscsi or drbd.

Hooking the `unmounted-remote-filesystems` and/or `runlevel [!$RUNLEVEL]` events with something that resolves and dismounts filesystems on network loopbacks would be the general solution.

This bug is unlikely to be fixed upstream, and it cannot be kludged in a generally safe and inexpensive way downstream, so I will eventually close this issue as a wontfix/dontdothat.  Anybody tracking ZoL issues should put a metoo on this ticket if they care about this issue and/or report it to distro (in context of a bundled filesystem).

For posterity, the bug expresses with this error message on the console:

```
CIFS VFS: Server linkstation has not responded in 120 seconds. Reconnecting...
CIFS VFS: Send error in read = -11
INFO: task txg_sync:4136 blocked for more than 120 seconds.
      Tainted: P           OE 3.16.0-23-generic #31-Ubuntu
```

**Comment by krichter722** [comment]
Thanks @dajhorn I'll look into that, but not provide feedback here as your (well appreciated) hint are a workaround only. Closing as wontfix/dontdothat seem reasonable.
