### ISSUE TITLE
Clarification on zfs-daily content

### ISSUE THREAD

**Issue by aqw** [zfsonlinux/pkg-zfs#153]
@FransUrbo @behlendorf 

Awhile ago there was some discussion about non-master patch-sets being included in the stable, tagged builds. It seems that the resolution of that discussion was that stable builds should remain vanilla.

Has any similar decision been made about the dailies? Today, I noticed that zfsonlinux/zfs#3337 showed up on one of my systems (which runs dailies) and that patch has not yet been merged into master. Furthermore, it includes a change in behavior (starting shares automatically) that was undocumented during install.

I do appreciate the effort that @FransUrbo puts into packaging, but providing packages is a position of trust. I need a clear understanding of what to expect from these packages, so that way I can make a decision about whether I should build my own. For me, a bare minimum is A) a list of (if any) any non-master patches included in the build B) clear notices about changes in behavior.

If dailies are intended to contain patches which have not yet been accepted into master, then it should be stated explicitly on the [ZoL Debian](http://zfsonlinux.org/debian.html) page and as a comment in the zfsonlinux.list file.

---Alex

**Comment by FransUrbo** [comment]
Have a look at <code>/usr/share/doc/zfsutils/README.Debian</code>.

For now I'm going to include 'stuff' in the Dailies that is (that **I**) consider safe. These is/can be things that does _NOT_ touch the core filesystem parts.

And just as a note bout #3337. That have, in essence, been in the packages for over a year. The only thing is that it's now been rewritten slightly (yes, slightly) because of comments in the PR. But the basic code base have been there 'for ever'. Also, since that is considered to belong to the packaging, that's my prerogative to add as I please.

That being said, there's not much 'extra stuff' that is of interest to me to add. If someone wants something they consider important, I'm open minded about it. AS LONG AS it doesn't go any where near the code (the ADB PR is one I wanted to include, but didn't dare).
