### ISSUE TITLE
zfs-initramfs is missing from ~zfs-native

### ISSUE THREAD

**Issue by watercrossing** [zfsonlinux/pkg-zfs#186]
I can't boot from my zfs root as initrd does not contain the zfs and spl modules. These are not added to the initrd as the zfs-initramfs package has been removed from the [~zfs-native ppa](https://launchpad.net/~zfs-native/+archive/ubuntu/stable). For now a workaround seems to add this ppa: https://launchpad.net/~zfsroot/+archive/ubuntu/initramfs, which contains the initramfs.

**Comment by dajhorn** [comment]
@watercrossing, this feature is discontinued.

**Comment by watercrossing** [comment]
Ok, but then how should I get the initramfs to include zfs and spl modules? Your guide at https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-14.04-or-Later-to-a-Native-ZFS-Root-Filesystem probably needs updating, as it just says do `# update-initramfs -u`.

**Comment by dajhorn** [comment]
> Ok, but then how should I get the initramfs to include zfs and spl modules?

These drivers should not be loaded early because doing so often breaks automatic mounting.  Past that, putting the modules into `/etc/initramfs-tools/modules` should get the desired result here.

> Your guide at https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-14.04-or-Later-to-a-Native-ZFS-Root-Filesystem probably needs updating,

This document was created by ZoL end-users.  Unfortunately, the features necessary for this solution are currently unsupported by both the PPA and by Ubuntu distribution.

**Comment by dajhorn** [comment]
This feature is now in scope for Ubuntu downstream, so I will close this ticket.
