### ISSUE TITLE
zfs-initramfs fails with slow drives

### ISSUE THREAD

**Issue by rlaager** [zfsonlinux/pkg-zfs#21]
I'm using a KVM virtual machine for testing ZFS. The virtual machine sees its virtual disks as SCSI drives. For whatever reason, they don't show up in the Linux until 2-6 seconds too late for the initramfs. So my boot fails.

**Comment by rlaager** [comment]
Here's a patch which deals with this:
https://gist.github.com/1619096

It simply keeps trying to import the zpool, sleeping 1 second between attempts, up to a maximum of 10 times (10 seconds). If/when the import succeeds, it breaks out of the loop immediately. So it's adding essentially zero delay to existing working cases, and it fixes my case.

**Comment by rlaager** [comment]
I switched to the linux-virtual kernel package and the delay is gone. Now the initramfs works great, even without the sleep. If you want to skip this patch, that's fine by me. But it does add some robustness.

**Comment by dajhorn** [comment]
If I add this patch, then I will change it to require a kernel option in the `/etc/default/grub` file so that the problem isn't masked.  My perspective on this ticket is:
- Ubuntu has a history of breaking -virtual and making -generic unnecessarily incompatible with VMs.  (eg: LP #546929 and LP #658461)
- Keeping the bug latent could induce somebody to figure out why `udevadm settle` is inadequate and fix the problem more generally.

Right now, I'm thinking that the root cause is an Ubuntu-specific kernel quirk.

**Comment by rlaager** [comment]
Since the -virtual kernel works fine, I'll just close the issue.

I definitely hear you on the first point. We're both subscribers on the second bug. On the second, though, I'm not sure that udevadm settle is doing anything wrong. From udev's point of view, and probably even the kernels', there simply is no sda at that point. It spontaneously appears (as if plugged in, I suppose) later. At least that's how it appears to behave to me. There's nothing for about 3 seconds and then all of a sudden, there's more dmesg output for a SCSI drive.

**Comment by dajhorn** [comment]
Okay, and the problem could also be in KVM because boot devices should never be a hotplug event after POST.

I noticed that you are working on the virt-manager backend.  Note that the qemu-kvm stack in Oneiric has some unusual bugs running on ZFS. I've noticed that:
- qcow2 images are sometimes truncated; the UI creates them and immediately complains that they are malformed.
- zvols are sometimes reported as zero size.

**Comment by rlaager** [comment]
What do you mean "reported as zero size"? It's zvols that I'm mainly concerned with supporting in a storage backend, at least initially.

**Comment by dajhorn** [comment]
When I tried to migrate my VBox and VMware data, KVM would spontaneously fail to start virtual machines that had devices backed by zvols.  The log said something about the zvol being too small, and debugging messages said zero bytes.

This happened a few months ago on Natty and Oneiric, and qemu-kvm was generally too incomplete for me to put any time into diagnosis.  No other application would choke on a zvol, so I figured that the problem was in KVM.

I will open a ticket with a useful error transcript if I try your branch and get this behavior.  :)
