### ISSUE TITLE
Does not build on Debian, wrong dependencies

### ISSUE THREAD

**Issue by rkaw92** [zfsonlinux/pkg-zfs#31]
Upon running dpkg-buildpackage on Squeeze, I get this error:

dpkg-checkbuilddeps: Unmet build dependencies: dkms (>> 2.1.1.2-5ubuntu1)

Moreover, zfs-initramfs seems to depend on zfs-grub, which
a) is not built at all (doesn't seem to exist, actually)
b) is unreasonable, since initramfs and GRUB are completely independent, and one could, for example, use LILO or require ZFS in initramfs despite booting from ext2.

The above problems make pkg-zfs unusable on Debian at the moment.

**Comment by dajhorn** [comment]
> Upon running dpkg-buildpackage on Squeeze, I get this error:
> 
> dpkg-checkbuilddeps: Unmet build dependencies: dkms (>> 2.1.1.2-5ubuntu1)

This dependency does indeed apply to Debian Squeeze even though it has "ubuntu" in the version string.  If you want to build pkg-zfs from source on Debian Squeeze, then you must also upgrade the `dkms` package.

> Moreover, zfs-initramfs seems to depend on zfs-grub, which
> a) is not built at all (doesn't seem to exist, actually)

The zfs-grub package is kept in a separate PPA because most users don't need it, and because it is known to be incompatible with vanilla Debian systems.

> b) is unreasonable, since initramfs and GRUB are completely independent, and one could, for example, use LILO

This is true for Debian, but false for Ubuntu, which is the primary build target.

I will certainly accept any patches that improve Debian support.

> or require ZFS in initramfs despite booting from ext2.

Having `/` in ext2 with any of `/etc`, `/lib`, `/bin`, or `/sbin` in ZFS will never be a supported configuration because ZoL is extrinsic to the Linux kernel.  (And most Linux distros can't do this with built-in drivers regardless.)

> The above problems make pkg-zfs unusable on Debian at the moment.

Just use the binary packages until you become familiar with building source packages.

**Comment by rkaw92** [comment]
Does zfs-grub really need to be a build-dep? What prevents it from being a Recommends: to the resulting package?
Could the package work with just dkms 2.1.1.2-5? It could be useful to loosen the dependencies...

About using binary packages, I thought those were not distributable?

**Comment by dajhorn** [comment]
> Does zfs-grub really need to be a build-dep?

No, but it has the beneficial side effect of forcing people to think twice, which is why it is still there.  Several people have damaged their computers by meddling in the initramfs code or init stack.

This has been discussed a few times on the ZoL support list, and I intend to properly fix it if/when I begin to do regular Debian testing.

> Could the package work with just dkms 2.1.1.2-5?

I don't remember whether that version has all of things that ZoL needs.  It would be easier to install the dkms package from Debian Wheezy or the patched version from the PPA.

> About using binary packages, I thought those were not distributable?

The PPA packages satisfy all GPL and CDDL obligations.  Neither spl-dkms nor zfs-dkms actually contain binary `.ko` objects.  DKMS builds the non-redistributable components after deb installation.
