### ISSUE TITLE
update to 1.99-21ubuntu3.1 seems to have broken Precise grub2 ZFS install

### ISSUE THREAD

**Issue by buffyg** [zfsonlinux/pkg-zfs#36]
Following the wiki directions, I've tried to set up an rpool. The grub install pieces appear to be broken ATM because Precise has updated to a later version, which means that apt will pick up that version even though the PPA is the preferred source. Thus I get the following error:

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 grub-common:i386 : Depends: libdevmapper1.02.1:i386 (>= 2:1.02.36) but it is not going to be installed
                    Depends: gettext-base:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

The subsequent attempt at zfs-initramfs install breaks because it can't replace the zfs-grub alias because the dependencies can't be solved.

**Comment by dajhorn** [comment]
This configuration is known to be incompatible with 32-bit systems, so I will close this ticket.

The reported error happened because grub was installed before ubuntu-zfs, which provides the necessary package pinning.  If you try again with a 64-bit computer, then follow the instructions exactly.

**Comment by buffyg** [comment]
I am using this with an amd64 system. I'm therefore unsure why there are i386 references popping up. Here's the output of apt-cache policy grub2:

grub2:
  Installed: 1.99-21ubuntu3.1
  Candidate: 1.99-21ubuntu3.1
  Version table:
 **\* 1.99-21ubuntu3.1 0
        500 http://gb.archive.ubuntu.com/ubuntu/ precise-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     1.99-21ubuntu3+zfs1 0
        900 http://ppa.launchpad.net/zfs-native/grub/ubuntu/ precise/main amd64 Packages
     1.99-21ubuntu3 0
        500 http://gb.archive.ubuntu.com/ubuntu/ precise/universe amd64 Packages
     1.98-1ubuntu12 0
        500 http://64.repository.backtrack-linux.org/ revolution/main amd64 Packages
     1.98-1ubuntu11 0
        500 http://64.repository.backtrack-linux.org/ revolution/main amd64 Packages
     1.98-1ubuntu10 0
        500 http://64.repository.backtrack-linux.org/ revolution/main amd64 Packages
     1.98-1ubuntu5 0
        500 http://64.repository.backtrack-linux.org/ revolution/main amd64 Packages

**Comment by buffyg** [comment]
Just to be clear about where i've varied from the HOWTO, I'm attempting to take a working install, transfer it to an rpool, and add the PPAs at that point. It looks like having an updated install may cause the image to have merge conflicts. The documentation indicates that this should work, but perhaps that's not a durable assumption?

**Comment by dajhorn** [comment]
Double-check that the installed binaries are actually 64-bit.  For example:

```
# file /usr/sbin/grub-probe
/usr/sbin/grub-probe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x1e2618f448769c8750e36491f6561fc77ad2e0ca, stripped
```

If you are doing this in a virtual machine, then I would start over.  Otherwise, the easiest fix is to manually download and install over the broken packages.  The full list for each PPA is:

https://launchpad.net/~zfs-native/+archive/stable/+packages
https://launchpad.net/~zfs-native/+archive/grub/+packages

Do these first:

https://launchpad.net/~zfs-native/+archive/grub/+files/grub-common_1.99-21ubuntu3%2Bzfs1_amd64.deb
https://launchpad.net/~zfs-native/+archive/grub/+files/grub-pc-bin_1.99-21ubuntu3%2Bzfs1_amd64.deb
https://launchpad.net/~zfs-native/+archive/grub/+files/grub2-common_1.99-21ubuntu3%2Bzfs1_amd64.deb
https://launchpad.net/~zfs-native/+archive/grub/+files/grub2_1.99-21ubuntu3%2Bzfs1_amd64.deb
https://launchpad.net/~zfs-native/+archive/stable/+files/ubuntu-zfs_6~precise_amd64.deb

Others could be required.

Run `dpkg --force-help` if it tells you that something must be forced.

**Comment by dajhorn** [comment]
All of the gotchas that come with a cloned system still happen, so the assumption only holds for basic configurations.

At a minimum, you must also manually update the `/boot/grub` modules after getting the right grub package installed.

**Comment by Nowaker** [comment]
Getting same error:

```
[ubuntu][/] # apt-get install zfs-grub
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'grub-common:i386' instead of 'zfs-grub'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 grub-common:i386 : Depends: libdevmapper1.02.1:i386 (>= 2:1.02.36) but it is not going to be installed
                    Depends: libfuse2:i386 (>= 2.8.1) but it is not going to be installed
                    Depends: libnvpair1:i386 but it is not installable
                    Depends: libuutil1:i386 but it is not installable
                    Depends: libzfs1:i386 but it is not installable
                    Depends: gettext-base:i386 but it is not going to be installed
                    Recommends: os-prober:i386 (>= 1.33) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

```
[ubuntu][/] # file `which grub-probe `
/usr/sbin/grub-probe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0xed1d52eb0aa8f7bf418946043bfc4cacd81eef0c, stripped
```

**Comment by dajhorn** [comment]
What is the output of these commands?

```
 # ls /var/cache/apt/archives
 # ls /etc/apt/sources.list.d
 # apt-cache policy grub-common
 # apt-cache depends grub-common
```

Are there any `*_i386.deb` files in the archive directory?

APT resolving an i386 package on an amd64 system is fatal in this circumstance.  We need to figure out why APT thinks an i386 package is even a possibility.

Note that hybrid X32 systems are known to incompatible, and ZoL won't be tested on them until distro release.  If you are using a backport to get that feature on Precise, then please revert it.

**Comment by Nowaker** [comment]
I already resolved the problem. Dist upgrade from 11.10 to 12.04 failed in the end, leaving some packages unconfigured. I had to:
- manually remove postrm scripts from /var/lib/dpkg/info/ for packages that needed to be removed but postrm scripts failed because of `grub-probe` fail for root, and then invoke `dpkg --remove --force-remove-reinstreq package1 package2`
- `dpkg -a --configure` packages that haven't been yet configured
- remove **all** ZFS packages and GRUB related packages
- add newest PPAs, zfs and grub, and install it

I can't tell the order becuase it was somewhat random. :-)

Why apt thinks about i386, no idea. However, my guess is:
- ppa:zfs-native/stable installed its own GRUB in my Ubuntu 11.10
- during the dist-upgrade to 12.04, zfs was deleted
- zfs-grub however still remained
- ...problems.

P.S. `apt-cache policy grub-common` was the same to @buffyg's.
