### ISSUE TITLE
Forcing mountpoint in initramfs breaks mountall

### ISSUE THREAD

**Issue by wrouesnel** [zfsonlinux/pkg-zfs#66]
I've been trying to track down the very odd behavior of mountall on my system, and I've narrowed it down to the following segment in ZFS initramfs script:

```
# Force the mountpoint to the only correct value for a root filesystem.
[ "$quiet" != "y" ] && log_begin_msg "Setting mountpoint=/ on ZFS filesystem $ZFS_BOOTFS"
ZFS_STDERR=$(zfs set mountpoint=/ "$ZFS_BOOTFS" 2>&1)
[ "$quiet" != "y" ] && log_end_msg
```

Commenting out this line makes mountall run correctly and mount all my ZFS filesystems at boot (and lets me put the correct fstab entry for the filesystem in). Leaving it in yields the following error in boot.log:

```
spawn: mount -f -t zfs -o defaults ssdpool/ROOT/mint-13 /
spawn: mount / [779]
filesystem 'ssdpool/ROOT/mint-13' cannot be mounted using 'mount'.
Use 'zfs set mountpoint=legacy' or 'zfs mount ssdpool/ROOT/mint-13'.
See zfs(8) for more information.
```

And results in my root being mounted (from initramfs) but no other ZFS filesystems being mounted.

My fstab (for the above) looks like this:

```
proc            /proc           proc    nodev,noexec,nosuid 0       0

# SSD /boot device
UUID=f3f17c64-78eb-42b9-b673-d5c2d830a321   /boot   ext2    defaults    0   1

# SSD swap device
UUID=6dfca925-6e31-42d1-8435-269caa992794   none    swap    sw  0   0
```

Removing that section though, and using the fstab below:

```
proc            /proc           proc    nodev,noexec,nosuid 0       0

# SSD ZFS legacy mount root
ssdpool/ROOT/mint-13                /   zfs defaults    0   0

# SSD /boot device
UUID=f3f17c64-78eb-42b9-b673-d5c2d830a321   /boot   ext2    defaults    0   1

# SSD swap device
UUID=6dfca925-6e31-42d1-8435-269caa992794   none    swap    sw  0   0
```

yields completely successful mounting of all ZFS filesystems.

Near as I can tell, forcing the root filesystem's mountpoint to '/' is exactly the wrong thing to do, given the way the initramfs and mountall interact. It seems like the correct answer would be to force it to legacy (since / should never be unmounted in normal operation by ZFS anyway), _or_ mountall needs to be changed to ignore the mount failure for /.

Of course it's possible this is a result of my non-pure ZFS setup, but in that case the solution would be check if the root FS is marked as a legacy mount and not change it's mountpoint if it is.

**Comment by dajhorn** [comment]
> Near as I can tell, forcing the root filesystem's mountpoint to '/' is exactly the wrong thing to do, given the way the initramfs and mountall interact. 

I recall three reasons for having that line:
- It was necessary for pivoting more than one mount point (which is currently broken).
- Old kernels during the 0.5 release series would randomly panic without it.
- To preserve Solaris behavior for ticket dajhorn/pkg-zfs#24.

This goes back to the Karmic release (or earlier), so let me check whether having it is still beneficial for currently supported Ubuntu releases.

> Commenting out this line makes mountall run correctly and mount all my ZFS filesystems at boot (and lets me put the correct fstab entry for the filesystem in). Leaving it in yields the following error in boot.log:
> 
> ```
> spawn: mount -f -t zfs -o defaults ssdpool/ROOT/mint-13 /
> ```

The `boot.log` is empty on a vanilla Precise system that is properly configured, which makes me think that the root mount is happening here too late.

> Removing that section though, and using the fstab below ... yields completely successful mounting of all ZFS filesystems.

This is expected behavior given the earlier `spawn: mount` error.  Any ZFS dataset that is mentioned in the `/etc/fstab` file or mounted by `/bin/mount` must have the `mountpoint=legacy` property.

Let me also check whether Nadia shipped something that is overriding the PPA.

**Comment by dajhorn** [comment]
I tried Linux Mint 14.  The problem is:
1. Nadia is based on Quantal.
2. The grub packages in Quantal have baked-in support for ZFS.
3. But support for the ZoL implementation is incomplete.
4. And the PPA does not have a supplemental fix because I am not supporting Quantal in this configuration.

The best solution is to put the root filesystem into the `/etc/fstab` file like you did earlier.

Downgrading to the packages for Precise incompletely resolves glitch for me -- I get search directive gunk in the `grub.cfg` file -- but it might work for you.

I will look at this issue again when Raring goes into beta, but in the meantime, I am tagging it as deferred.

And a point that I missed earlier...

> It seems like the correct answer would be to force it to legacy (since / should never be unmounted in normal operation by ZFS anyway), or mountall needs to be changed to ignore the mount failure for /.

This is an unsafe assumption because some people do system upgrades through cloning or snapshot promotion. A system could have several instances of `mountpoint=/` with `canmount=off` and descendant datasets.

**Comment by wrouesnel** [comment]
Ok so following up on this a bit more, it does appear it's the original line, but not for the reason I thought - I had an old copy of zfs-initramfs actually installed which used `ZFS_STDERR=$(zfs set -o mountpoint=/ "$ZFS_BOOTFS" 2>&1)` as the ZFS_STDERR line, so everytime I mounted root the filesystem never actually got set away from legacy (since that's an invalid command).

I still get an occasional failure to mount for some reason after a few reboots, but that is most likely from a different cause - closing this issue.

**Comment by wrouesnel** [comment]
So it seems my initial analysis wasn't correct. The behavior is as I reported it before, it's just not consistent: every second boot, mountall will try and mount the root as a regular filesystem, and fail to do so - leading to no other ZFS datasets being mounted. If I then reboot immediately (via `reboot`) then everything will mount successfully - although tellingly, `mount` does not show the ZFS dataset on the list of mounted filesystems.

**Comment by FransUrbo** [comment]
The Debian GNU/Linux Wheezy snapshot/daily packages have had their initrd scripts almost completely rewritten so I can't see this as a problem in Debian GNU/Linux. Tagging appropriately.

**Comment by dajhorn** [comment]
ZoL initramfs features were deprecated and discontinued in the PPA, and partially continued downstream as of the Ubuntu 16.06 LTS release, so I will close this ticket as stale.
