### ISSUE TITLE
Installing ZFS on root for Ubuntu 11.10

### ISSUE THREAD

**Issue by Nowaker** [zfsonlinux/pkg-zfs#7]
I followed your instructions but instead of natty I debootstrapped oneiric. I get:

```
root@ubuntu:/# apt-add-repository ppa:zfs-native/stable
You are about to add the following PPA to your system:
 ZFS Stable Releases for Ubuntu
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 80, in <module>
    print " %s" % (ppa_info["description"] or "")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 522-523: ordinal not in range(128)
```

To install it without any error I had to:

   apt-add-repository ppa:zfs-native/stable --yes

You could include it in the tutorial.

**Comment by dajhorn** [comment]
If you do this again, then please try running this command before adding the repository:

```
  # locale-gen en_US.UTF-8
```

This issue was reported earlier to the support list in this thread:

http://groups.google.com/a/zfsonlinux.org/group/zfs-discuss/browse_thread/thread/8149b49858a3fa66/75207ff7113b6d5e

I will leave this ticket open until I can reproduce the problem and update the HOWTO document.

**Comment by Nowaker** [comment]
Thanks for letting me know. I won't probably try it out since I already have a working Ubuntu with ZFS.

**Comment by thw-zz** [comment]
i had the same issue while installing from 11.10. desktop amd64.
After executing 

   # locale-gen en_US.UTF-8 

adding the ppa's

   # apt-add-repository ppa:zfs-native/stable
   # apt-add-repository ppa:zfs-native/stable

went without the errors.

**Comment by dajhorn** [comment]
The wiki page is updated for Ubuntu 11.10 (Oneiric).  Thanks for the bug report and updated instructions.

**Comment by thw-zz** [comment]
Hi Darik,

you might move the locale-gen statement directly behind apt-get update.
This would also remove a warning during python-software-properties installation.

```
    Get:6 http://archive.ubuntu.com/ubuntu/ oneiric/main python-software-properties all 0.81.10 [19.7 kB]
    Fetched 3944 kB in 1s (2599 kB/s)                
    perl: warning: Setting locale failed.
    perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
        are supported and installed on your system.
    perl: warning: Falling back to the standard locale ("C").
    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
    locale: Cannot set LC_ALL to default locale: No such file or directory
    Preconfiguring packages ...
```

debootstrap does little to nothing regarding the locale.
/var/lib/locales/supported.d/ is empty
/usr/lib/locale only contains C.UTF-8/ and no locale-archive, which indicates that locale-gen was never executed.

Unfortunatelly, the current environment pretends to have LANG=en_US.UTF-8

```
    # env | grep LANG
    LANG=en_US.UTF-8
```

btw: apt-get install ubuntu-minimal does nothing; seems to be identical to what debootstrap installs

```
    # apt-get install ubuntu-minimal
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    ubuntu-minimal is already the newest version.
    .....
```

Regards 
Thomas

**Comment by dajhorn** [comment]
Okay, I applied this change.

I put ubuntu-minimal into the package list because people were doing installs into a basic imaged systems that didn't have it installed, like at some VPS hosts, and skipping the debootstrap step.  Other system tweakers would remove ubuntu-minimal for server installations and then complain that DKMS was broken.

**Comment by thw-zz** [comment]
dkms mkdeb (your tip; step 5.6b) is anyway not working. it complains that spl-0.6.0 and zfs-0.6.0 are not in the
dkms tree. Since i am a complete newbie with regards to ubuntu (and linux in generall) i have no clue how to get
this working. If it doesnt take to much efforts, you eventually could add the missing pieces to the tip section.

And, from a newbie POV, i have a suggestion for the troubleshooting section. Please include the hint, that the system
might have booted correctly after following the howto and does anyway show up a blank black screen. 
I run in this vt.handoff=7 issue and it took me 3 or 4 complete restarts until i accidentally discoverd that the system 
was running and that i could switch to tty1 using Alt-F1.

A possible solution could be to edit /etc/default/grub before update-grub, changing

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"

to

GRUB_CMDLINE_LINUX_DEFAULT="quiet"

This removes the vt.handoff=7 parameter from the boot config, and the system comes up with tty1 active.

BTW, that will open an other can of worms - you see a bunch of udev error messages on the screen:
udevd[] failed to execute  '/lib/udev/zpool_id' '/lib/udev/zpool_id  -d /devices/virtual/block/.... ' : No such file or directory
but this is surely out of scope for this howto. This issue was new for me with 11.10+rc6; 11.04+rc5 didnt show
this behavior.

**Comment by dajhorn** [comment]
The hint in step 5 is incomplete because DKMS always requires the full version.  Substitute `0.6.0` for `0.6.0.36` or whatever happens to be currently installed.  I will think about how to word this properly.

The blank boot screen is a bug in Ubuntu that affects some hardware configurations and, I think, VirtualBox too.  I am unsure about whether to give treatment to general bugs in this document.

The udev errors for zvols are spurious at boot time for Oneiric, but I expect that they will require fixing before Precise is released.

**Comment by thw-zz** [comment]
dkms is ok using the the full version. Sorry from the newbie.

After solving the blank screen problem for my case, i have the feeling that this error is kind of "fixed"
as /etc/grub.d/10_linux passes this vt.handoff parameter only if it is configured to do so. Earlier versions
passed this parameter unconditional, but now only if configuered with "splash". Unfortunatelly the defaults 
for grub in /etc/default/grub are "quiet splash". 

Relying on this howto (debootstrap + ubuntu-minimal) gets you directly into trouble since ubuntu-minimal
has plymouth installed, but no themes, no sufficent graphics subsystem, dont even start plymouthd and
has grub defaults "quiet splash".

Do you have any idea about issue8 i opend yesterday? I cannot get grub installed via /dev/disk/by-id addressing.
After a lot time searching the internet, i got no working solution. Funnily when grub-install fails with that grub-probe 
error, grub-probe /dev/sda fails also but grub-install /dev/sda works.

**Comment by dajhorn** [comment]
I need to reproduce and diagnose issue dajhorn/pkg-zfs#8.  It isn't immediately obvious whether the glitch is in udev, grub, or elsewhere.

Plymouth is something that you must tolerate.  If you work under the hood on Ubuntu, then you'll notice several more things like it.
